apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: payments-ms-webhook
  name: payments-ms-webhook
spec:
  ports:
  - name: "3003"
    port: 3003
    protocol: TCP
    targetPort: 3003
  selector:
  # this name must match the name of the deployment
    app: payments-ms
  type: NodePort
status:
  loadBalancer: {}
